#FILL IN THE SETTINGS DATA USING YOUR OWN API KEYS AND DIRECTORIES
#YOU NEED TO PROVIDE ALL OF THEM FOR THE APP TO WORK

IMAGE_DIR = ''
TEXTPROCESS_DIR = ''
GOOGLE_API_KEY = ""
GOOGLE_EN_ENGINE_KEY = ""
GOOGLE_UNIVERSAL_ENGINE_KEY = ""
FARSI_MODEL_DATA_DIR = ""
GOOGLE_DALISYRON_ENGINE = ""
GOOGLE_DALISYRON_API_KEY = ""